config/routes.rb
Rails.application.routes.draw do

   root 'index#index'

   namespace :admin do 
    resources :services do 
      collection do
        get 'top'
      end
    end
    resources :intros do 
      collection do
        get 'top'
      end
    end
    resources :advts do 
      collection do
        get 'top'
      end
    end
    resources :questions do 
      collection do
        get 'top'
      end
    end
    resources :service_items do 
      collection do
        get 'top'
      end
    end
    resources :newses do 
      collection do
        get 'top'
      end
    end
    resources :cases do 
      collection do
        get 'top'
      end
    end
   end

  get "/index/product" => "index#product"
  get "/index/product/:id" => "index#product"
  get "/index/news" => "index#news"
  get "/index/news/:id" => "index#news"
  get "/index/case" => "index#case"
  get "/index/case/:id" => "index#case"
  get "/index/about" => "index#about"
  get "/index/intro" => "index#intro"
  get "/index/question" => "index#question"
  get "/index/question/:id" => "index#question"

end

app/models/advt.rb
class Advt < ActiveRecord::Base
	mount_uploader :image, AdvtUploader
end

app/models/case.rb
class Case < ActiveRecord::Base
  mount_uploader :image, AdvtUploader
end

app/models/intro.rb
class Intro < ActiveRecord::Base
	mount_uploader :image, AdvtUploader
end

app/models/newse.rb
class Newse < ActiveRecord::Base
  self.table_name = "news"
  mount_uploader :image, AdvtUploader
end

app/models/question.rb
class Question < ActiveRecord::Base
end

app/models/service.rb
class Service < ActiveRecord::Base
	
end

app/models/service_item.rb
class ServiceItem < ActiveRecord::Base
  mount_uploader :image, AdvtUploader
  belongs_to :service
end

app/models/stat.rb
class Stat < ActiveRecord::Base
end

app/controllers/admin/advts_controller.rb
class Admin::AdvtsController <  AdminBaseController
	def index
		@advts = Advt.all.order("updated_at desc")
	end

	def new
		@advt = Advt.new
	end 

	def create
		@advt = Advt.new(advt_params)
		@advt.save
		$advts = nil
		redirect_to admin_advts_path
	end

	def destroy
		@advt = Advt.find_by_id(params[:id])
		@advt.delete
		$advts = nil
		redirect_to admin_advts_path
	end

	def top
		advt = Advt.find_by_id(params[:id])
		advt.update(updated_at: Time.now)
		$advts = nil
		redirect_to admin_advts_path
	end

	private 
	def advt_params
      params.require(:advt).permit(:name, :image)
    end
end

app/controllers/admin/cases_controller.rb
class Admin::CasesController < AdminBaseController

  def index
    @cases = Case.order("updated_at desc").page(params[:page])
  end

  def new
    @case = Case.new()
  end

  def create
    ca = Case.new(case_params)
    ca.save
    $cases = nil
    redirect_to admin_cases_path
  end

  def destroy
    ca = Case.find_by_id(params[:id])
    ca.delete
    $cases = nil
    redirect_to admin_cases_path
  end

  def top
    ca = Case.find_by_id(params[:id])
    ca.update(updated_at: Time.now)
    $cases = nil
    redirect_to admin_cases_path
  end

  def edit
    @case = Case.find_by_id(params[:id])
  end

  def update
    ca = Case.find_by_id(params[:id])
    ca.update(case_params)
    $cases = nil
    redirect_to admin_cases_path
  end

  private 

  def case_params
      params.require(:case).permit(:name, :image, :context)
  end


end

app/controllers/admin/service_items_controller.rb
class Admin::ServiceItemsController <  AdminBaseController
  def index
    @service_items = ServiceItem.order("updated_at desc").page(params[:page])
  end

  def new
    @service_item = ServiceItem.new
  end

  def show
    @service_item = ServiceItem.find_by_id(params[:id])
  end

  def edit
    @service_item = ServiceItem.find_by_id(params[:id])
  end

  def update
    @service_item = ServiceItem.find_by_id(params[:id])
    @service_item.update(service_item_permit)
    $products = nil
    redirect_to admin_service_items_path
  end

  def create
    @service_item = ServiceItem.new(service_item_permit)
    @service_item.save
    $products = nil
    redirect_to admin_service_items_path
  end

  def destroy
    service_item = ServiceItem.find_by_id(params[:id])
    service_item.delete
    $products = nil
    redirect_to admin_service_items_path
  end

  def top
    service_item = ServiceItem.find_by_id(params[:id])
    service_item.update(updated_at: Time.now)
    $products = nil
    redirect_to admin_service_items_path
  end


  private 
  def service_item_permit
    params.require(:service_item).permit(:service_id,  :desc, :content, :image, :name)
  end
end

app/controllers/admin_base_controller.rb
class AdminBaseController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout "admin"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  layout "fro"

  before_action :init
  
	def index
    @news = $newses.first
	end

  def product
    if params[:id].present?
      @service_item = ServiceItem.find_by_id(params[:id])
    end
    @service_item  ||= ServiceItem.order("updated_at desc").first
    @service_items = ServiceItem.where.not(id: @service_item.id).order("updated_at desc").limit(10)
  end

  def news
    if params[:id].present?
      @news = Newse.find_by_id(params[:id])
    end
    @news ||= Newse.order("updated_at desc").first
    @newses = $newses.select{|x| x.id != @news.id}
  end

  def about

  end

  def intro
     @service_items = ServiceItem.order("updated_at desc").limit(4)
  end

  def case
    if params[:id].present?
      @case = Case.find_by_id(params[:id])
    end
    @case ||= Case.order("updated_at desc").first
    @cases = $cases.select{|x| x.id != @case.id }
  end


  def question
    if params[:id].present?
      question = Question.find_by_id(params[:id])
    end
    @question ||= Question.order("updated_at desc").first
    @questions = $questions.select{|x| x.id != question.id }
  end


  def init 
    $intro ||= Intro.last
    $services ||= Service.order("updated_at desc")
    $questions ||= Question.order("updated_at desc").limit(8)
    $advts ||= Advt.order("updated_at desc").limit(3)
    $newses ||= Newse.order("updated_at desc").limit(10)
    $cases  ||= Case.order("updated_at desc").limit(10)
    $products ||= $services.map{|service| ServiceItem.where(service_id: service.id).order("updated_at desc").limit(1).first}.select{|si| si.present?}
  end

  


end

app/helpers/admin/advts_helper.rb
module Admin::AdvtsHelper
end

app/helpers/admin/cases_helper.rb
module Admin::CasesHelper
end

app/helpers/admin/intros_helper.rb
module Admin::IntrosHelper
end

app/helpers/admin/newses_helper.rb
module Admin::NewsesHelper
end

app/helpers/admin/questions_helper.rb
module Admin::QuestionsHelper
end

app/helpers/admin/service_items_helper.rb
module Admin::ServiceItemsHelper
end

app/helpers/admin/services_helper.rb
module Admin::ServicesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/views/admin/service_items/edit.html.erb
<div class="title">
    <h2><i class="fa "></i>项目内容</h2>
</div>
<%= form_for [:admin, @service_item], html: {id:"Forms", role: "form" }  do |f| %>
  <table class="tab2 mt20">
  <tr>
      <td width="100" class="bold right">标题</td>
      <td>
        <%= f.text_field :name %>
      </td>
    </tr>
    <tr>
      <td width="100" class="bold right">所属项目</td>
      <td>
        <%= f.select :service_id, options_for_select(Service.all.map{|x| [x.name, x.id]}), {}, class: "" %>
      </td>
    </tr>

    <tr>
      <td width="100" class="bold right">图片</td>
      <td>
        <%= f.file_field :image %>
      </td>
    </tr>

    <tr>
      <td width="100" class="bold right">简答描述</td>
      <td>
        <%= f.text_area :desc, rows: 4, cols: 100 %>
      </td>
    </tr>

    <tr>
      <td width="100" class="bold right">详细内容</td>
      <td>
        <%= f.kindeditor :content%>
      </td>
    </tr>

    <tr>
        <td>&nbsp;</td>
        <td style="padding-top:75px;">
          <button class="btn3 mr20" type="submit"><i class=" "></i>完成</button>
          <button onclick="history.go(-1)" class="btn4" type="button"><i class=" "></i>返回</button>
        </td>
      </tr>
  </table>
<% end %>

app/views/admin/service_items/index.html.erb
<div class="title">
   <%= form_tag admin_service_items_path, method: :get do %>
    <h2><i class="fa "></i>项目内容</h2>
    <div class="titlebox">
      <a class="btn2" href="/admin/service_items/new"><i class="fa"></i>添加内容</a>
    </div>
  <% end %> 
</div>

<div class="tabbox1">
  <table class="tab1 mt30">
    <thead>
      <tr>
        <th>所属项目</th>
        <th>内容简介</th>
        <th>操作</th>
      </tr>
    </thead>
    <tbody>
      <% @service_items.each do |service_item| %>
        <tr class="center">
          <td><%= Service.find_by_id(service_item.service_id).try(:name) %></td>
          <td><%= service_item.desc %></td>
          <td class="action-buttons">
            <%= link_to "修改", edit_admin_service_item_path(service_item), class: "blue " %>
            <%= link_to "置顶", "/admin/service_items/top?id=#{service_item.id}", class: "blue " %>
            <%= link_to "删除", [:admin, service_item], method: :delete, data: {confirm: "确定删除?"}, title:"删除", class:"red  " %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @service_items %>
</div>

app/views/admin/service_items/new.html.erb
<div class="title">
    <h2><i class="fa "></i>项目内容</h2>
</div>
<%= form_for [:admin, @service_item], html: {id:"Forms", role: "form" }  do |f| %>
  <table class="tab2 mt20">
  <tr>
      <td width="100" class="bold right">标题</td>
      <td>
        <%= f.text_field :name %>
      </td>
    </tr>
    <tr>
      <td width="100" class="bold right">所属项目</td>
      <td>
        <%= f.select :service_id, options_for_select(Service.all.map{|x| [x.name, x.id]}), {}, class: "" %>
      </td>
    </tr>

    <tr>
      <td width="100" class="bold right">图片</td>
      <td>
        <%= f.file_field :image %>
      </td>
    </tr>

    <tr>
      <td width="100" class="bold right">简答描述</td>
      <td>
        <%= f.text_area :desc, rows: 4, cols: 100 %>
      </td>
    </tr>

    <tr>
      <td width="100" class="bold right">详细内容</td>
      <td>
        <%= f.kindeditor :content%>
      </td>
    </tr>

    <tr>
        <td>&nbsp;</td>
        <td style="padding-top:75px;">
          <button class="btn3 mr20" type="submit"><i class=" "></i>完成</button>
          <button onclick="history.go(-1)" class="btn4" type="button"><i class=""></i>返回</button>
        </td>
      </tr>
  </table>
<% end %>

app/views/admin/service_items/show.html.erb
<%= @service_item.content%>