config/routes.rb
Rails.application.routes.draw do

   root 'index#index'

   namespace :admin do 
    resources :services do 
      collection do
        get 'top'
      end
    end
    resources :intros do 
      collection do
        get 'top'
      end
    end
    resources :advts do 
      collection do
        get 'top'
      end
    end
    resources :questions do 
      collection do
        get 'top'
      end
    end
    resources :service_items do 
      collection do
        get 'top'
      end
    end
    resources :newses do 
      collection do
        get 'top'
      end
    end
    resources :cases do 
      collection do
        get 'top'
      end
    end
   end

  get "/index/product" => "index#product"
  get "/index/product/:id" => "index#product"
  get "/index/news" => "index#news"
  get "/index/news/:id" => "index#news"
  get "/index/case" => "index#case"
  get "/index/case/:id" => "index#case"
  get "/index/about" => "index#about"
  get "/index/intro" => "index#intro"
  get "/index/question" => "index#question"
  get "/index/question/:id" => "index#question"

end

app/models/advt.rb
class Advt < ActiveRecord::Base
	mount_uploader :image, AdvtUploader
end

app/models/case.rb
class Case < ActiveRecord::Base
  mount_uploader :image, AdvtUploader
end

app/models/intro.rb
class Intro < ActiveRecord::Base
	mount_uploader :image, AdvtUploader
end

app/models/newse.rb
class Newse < ActiveRecord::Base
  self.table_name = "news"
  mount_uploader :image, AdvtUploader
end

app/models/question.rb
class Question < ActiveRecord::Base
end

app/models/service.rb
class Service < ActiveRecord::Base
	
end

app/models/service_item.rb
class ServiceItem < ActiveRecord::Base
  mount_uploader :image, AdvtUploader
  belongs_to :service
end

app/models/stat.rb
class Stat < ActiveRecord::Base
end

app/controllers/admin/advts_controller.rb
class Admin::AdvtsController <  AdminBaseController
	def index
		@advts = Advt.all.order("updated_at desc")
	end

	def new
		@advt = Advt.new
	end 

	def create
		@advt = Advt.new(advt_params)
		@advt.save
		$advts = nil
		redirect_to admin_advts_path
	end

	def destroy
		@advt = Advt.find_by_id(params[:id])
		@advt.delete
		$advts = nil
		redirect_to admin_advts_path
	end

	def top
		advt = Advt.find_by_id(params[:id])
		advt.update(updated_at: Time.now)
		$advts = nil
		redirect_to admin_advts_path
	end

	private 
	def advt_params
      params.require(:advt).permit(:name, :image)
    end
end

app/controllers/admin/cases_controller.rb
class Admin::CasesController < AdminBaseController

  def index
    @cases = Case.order("updated_at desc").page(params[:page])
  end

  def new
    @case = Case.new()
  end

  def create
    ca = Case.new(case_params)
    ca.save
    $cases = nil
    redirect_to admin_cases_path
  end

  def destroy
    ca = Case.find_by_id(params[:id])
    ca.delete
    $cases = nil
    redirect_to admin_cases_path
  end

  def top
    ca = Case.find_by_id(params[:id])
    ca.update(updated_at: Time.now)
    $cases = nil
    redirect_to admin_cases_path
  end

  def edit
    @case = Case.find_by_id(params[:id])
  end

  def update
    ca = Case.find_by_id(params[:id])
    ca.update(case_params)
    $cases = nil
    redirect_to admin_cases_path
  end

  private 

  def case_params
      params.require(:case).permit(:name, :image, :context)
  end


end

app/controllers/admin_base_controller.rb
class AdminBaseController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout "admin"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  layout "fro"

  before_action :init
  
	def index
    @news = $newses.first
	end

  def product
    if params[:id].present?
      @service_item = ServiceItem.find_by_id(params[:id])
    end
    @service_item  ||= ServiceItem.order("updated_at desc").first
    @service_items = ServiceItem.where.not(id: @service_item.id).order("updated_at desc").limit(10)
  end

  def news
    if params[:id].present?
      @news = Newse.find_by_id(params[:id])
    end
    @news ||= Newse.order("updated_at desc").first
    @newses = $newses.select{|x| x.id != @news.id}
  end

  def about

  end

  def intro
     @service_items = ServiceItem.order("updated_at desc").limit(4)
  end

  def case
    if params[:id].present?
      @case = Case.find_by_id(params[:id])
    end
    @case ||= Case.order("updated_at desc").first
    @cases = $cases.select{|x| x.id != @case.id }
  end


  def question
    if params[:id].present?
      question = Question.find_by_id(params[:id])
    end
    @question ||= Question.order("updated_at desc").first
    @questions = $questions.select{|x| x.id != question.id }
  end


  def init 
    $intro ||= Intro.last
    $services ||= Service.order("updated_at desc")
    $questions ||= Question.order("updated_at desc").limit(8)
    $advts ||= Advt.order("updated_at desc").limit(3)
    $newses ||= Newse.order("updated_at desc").limit(10)
    $cases  ||= Case.order("updated_at desc").limit(10)
    $products ||= $services.map{|service| ServiceItem.where(service_id: service.id).order("updated_at desc").limit(1).first}.select{|si| si.present?}
  end

  


end

app/helpers/admin/advts_helper.rb
module Admin::AdvtsHelper
end

app/helpers/admin/cases_helper.rb
module Admin::CasesHelper
end

app/helpers/admin/intros_helper.rb
module Admin::IntrosHelper
end

app/helpers/admin/newses_helper.rb
module Admin::NewsesHelper
end

app/helpers/admin/questions_helper.rb
module Admin::QuestionsHelper
end

app/helpers/admin/service_items_helper.rb
module Admin::ServiceItemsHelper
end

app/helpers/admin/services_helper.rb
module Admin::ServicesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/views/admin/cases/edit.html.erb
<div class="title">
    <h2><i class="fa "></i>修改案例</h2>
</div>
<%= form_for  [:admin, @case], html: {id:"Forms", role: "form" }  do |f| %>
  <table class="tab2 mt20">
    <tr>
      <td width="100" class="bold right">标题</td>
      <td>
        <%= f.text_field :name, class: "texts2 w450 l", required:"on", autofocus:"on", autocomplete:"off" %>
        <span class="notice">*</span>
      </td>
    </tr>
  
    <tr>
      <td class="bold right" valign="top">图片</td>
      <td>
        <%= f.file_field :image, class: "prizeImgfile", id: "UploadFile1" %>
      </td>
    </tr>

     <tr>
      <td class="bold right" valign="top">内容</td>
      <td>
        <%= f.kindeditor :context %>
      </td>
    </tr>
    <tr>
        <td>&nbsp;</td>
        <td style="padding-top:75px;">
          <button class="btn3 mr20" type="submit"><i class=""></i>完成</button>
          <button onclick="history.go(-1)" class="btn4" type="button"><i class=""></i>返回</button>
        </td>
      </tr>
  </table>
<% end %>

app/views/admin/cases/index.html.erb
<div class="title">
   <%= form_tag admin_cases_path, method: :get do %>
    <h2><i class="fa"></i>工程案例</h2>
    <div class="titlebox">
    <!--   <%= text_field_tag :name, params[:name], class: "texts w300 mt10", placeholder: '输入商家名称' %>
      <button class="btn1 mlr8" type="submit"><i class="glyphicon glyphicon-search"></i>搜索</button> -->
      <a class="btn2" href="/admin/cases/new"><i class=""></i>添加案例</a>
    </div>
  <% end %> 
</div>

<div class="tabbox1">
  <table class="tab1 mt30">
    <thead>
      <tr>
        <th>标题</th>
        <th>图片</th>
        <th>简介</th>
        <th>操作</th>
      </tr>
    </thead>
    <tbody>
      <% @cases.each do |ca| %>
        <tr class="center">
          <td><%= ca.name %></td>
          <td><%= image_tag  ca.image_url, class: "w200 h200" %></td>
          <td><%= truncate ca.context, length: 50 %></td>
          <td class="action-buttons">
            <%#= link_to "详情", admin_cases_path(ca), class: "blue fa fa-search-plus", title: "预览", target:"_blank" %>
            <%= link_to "修改", edit_admin_case_path(ca), class: "blue" %>
            <%= link_to "置顶", "/admin/cases/top?id=#{ca.id}", class: "blue" %>
            <%= link_to "删除", [:admin, ca], method: :delete, data: {confirm: "确定删除?"}, title:"删除", class:"red" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @cases %>
</div>

app/views/admin/cases/new.html.erb
<div class="title">
    <h2><i class="fa "></i>添加案例</h2>
</div>
<%= form_for  [:admin, @case], html: {id:"Forms", role: "form" }  do |f| %>
  <table class="tab2 mt20">
    <tr>
      <td width="100" class="bold right">标题</td>
      <td>
        <%= f.text_field :name, class: "texts2 w450 l", required:"on", autofocus:"on", autocomplete:"off" %>
        <span class="notice">*</span>
      </td>
    </tr>
  
    <tr>
      <td class="bold right" valign="top">图片</td>
      <td>
        <%= f.file_field :image, class: "prizeImgfile", id: "UploadFile1" %>
      </td>
    </tr>

     <tr>
      <td class="bold right" valign="top">内容</td>
      <td>
        <%= f.kindeditor :context %>
      </td>
    </tr>
    <tr>
        <td>&nbsp;</td>
        <td style="padding-top:75px;">
          <button class="btn3 mr20" type="submit"><i class=""></i>完成</button>
          <button onclick="history.go(-1)" class="btn4" type="button"><i class=""></i>返回</button>
        </td>
      </tr>
  </table>
<% end %>