config/routes.rb
Rails.application.routes.draw do

   root 'index#index'

   namespace :admin do 
    resources :services do 
      collection do
        get 'top'
      end
    end
    resources :intros do 
      collection do
        get 'top'
      end
    end
    resources :advts do 
      collection do
        get 'top'
      end
    end
    resources :questions do 
      collection do
        get 'top'
      end
    end
    resources :service_items do 
      collection do
        get 'top'
      end
    end
    resources :newses do 
      collection do
        get 'top'
      end
    end
    resources :cases do 
      collection do
        get 'top'
      end
    end
   end

  get "/index/product" => "index#product"
  get "/index/product/:id" => "index#product"
  get "/index/news" => "index#news"
  get "/index/news/:id" => "index#news"
  get "/index/case" => "index#case"
  get "/index/case/:id" => "index#case"
  get "/index/about" => "index#about"
  get "/index/intro" => "index#intro"
  get "/index/question" => "index#question"
  get "/index/question/:id" => "index#question"

end

app/models/advt.rb
class Advt < ActiveRecord::Base
	mount_uploader :image, AdvtUploader
end

app/models/case.rb
class Case < ActiveRecord::Base
  mount_uploader :image, AdvtUploader
end

app/models/intro.rb
class Intro < ActiveRecord::Base
	mount_uploader :image, AdvtUploader
end

app/models/newse.rb
class Newse < ActiveRecord::Base
  self.table_name = "news"
  mount_uploader :image, AdvtUploader
end

app/models/question.rb
class Question < ActiveRecord::Base
end

app/models/service.rb
class Service < ActiveRecord::Base
	
end

app/models/service_item.rb
class ServiceItem < ActiveRecord::Base
  mount_uploader :image, AdvtUploader
  belongs_to :service
end

app/models/stat.rb
class Stat < ActiveRecord::Base
end

app/controllers/admin/advts_controller.rb
class Admin::AdvtsController <  AdminBaseController
	def index
		@advts = Advt.all.order("updated_at desc")
	end

	def new
		@advt = Advt.new
	end 

	def create
		@advt = Advt.new(advt_params)
		@advt.save
		$advts = nil
		redirect_to admin_advts_path
	end

	def destroy
		@advt = Advt.find_by_id(params[:id])
		@advt.delete
		$advts = nil
		redirect_to admin_advts_path
	end

	def top
		advt = Advt.find_by_id(params[:id])
		advt.update(updated_at: Time.now)
		$advts = nil
		redirect_to admin_advts_path
	end

	private 
	def advt_params
      params.require(:advt).permit(:name, :image)
    end
end

app/controllers/admin_base_controller.rb
class AdminBaseController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout "admin"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  layout "fro"

  before_action :init
  
	def index
    @news = $newses.first
	end

  def product
    if params[:id].present?
      @service_item = ServiceItem.find_by_id(params[:id])
    end
    @service_item  ||= ServiceItem.order("updated_at desc").first
    @service_items = ServiceItem.where.not(id: @service_item.id).order("updated_at desc").limit(10)
  end

  def news
    if params[:id].present?
      @news = Newse.find_by_id(params[:id])
    end
    @news ||= Newse.order("updated_at desc").first
    @newses = $newses.select{|x| x.id != @news.id}
  end

  def about

  end

  def intro
     @service_items = ServiceItem.order("updated_at desc").limit(4)
  end

  def case
    if params[:id].present?
      @case = Case.find_by_id(params[:id])
    end
    @case ||= Case.order("updated_at desc").first
    @cases = $cases.select{|x| x.id != @case.id }
  end


  def question
    if params[:id].present?
      question = Question.find_by_id(params[:id])
    end
    @question ||= Question.order("updated_at desc").first
    @questions = $questions.select{|x| x.id != question.id }
  end


  def init 
    $intro ||= Intro.last
    $services ||= Service.order("updated_at desc")
    $questions ||= Question.order("updated_at desc").limit(8)
    $advts ||= Advt.order("updated_at desc").limit(3)
    $newses ||= Newse.order("updated_at desc").limit(10)
    $cases  ||= Case.order("updated_at desc").limit(10)
    $products ||= $services.map{|service| ServiceItem.where(service_id: service.id).order("updated_at desc").limit(1).first}.select{|si| si.present?}
  end

  


end

app/helpers/admin/advts_helper.rb
module Admin::AdvtsHelper
end

app/helpers/admin/cases_helper.rb
module Admin::CasesHelper
end

app/helpers/admin/intros_helper.rb
module Admin::IntrosHelper
end

app/helpers/admin/newses_helper.rb
module Admin::NewsesHelper
end

app/helpers/admin/questions_helper.rb
module Admin::QuestionsHelper
end

app/helpers/admin/services_helper.rb
module Admin::ServicesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/views/index/_left.html.erb
<div style="float: left; height: auto;">

    <div class="con1" style="margin: 20px 0; ">
      <div class="con1-l">
        <div class="con1-l-t">联系我们</div>
        <div class="con2-c-c" style="width: auto; font-size: 13px; height: 190px;">
          <p style="font-size: 17px; margin: 5px 0;"><%= $intro.name %></p>
              地址：<%= $intro.addr %><br />
              电话：0510-81151545<br />
              手机：<%= $intro.tel %><br />
              联系人：<%= $intro.user %><br />
              网址：www.wxhjj.com<br/>
              <!-- 邮箱：946992252@qq.com -->   
        </div> 
        </div>
        <div class="clear"></div>
    </div>

    <div class="con1">
        <div class="con1-l">
          <div class="con1-l-t">服务项目 Service Items</div>
            <ul class="iauth">
              <% $services.each do |service| %>
                  <li>
                      <%=link_to service.name, "", title: service.name %>
                  </li>
              <% end %>
            </ul>
          </div>
          <div class="clear"></div>
      </div>

       <div class="con1" style="margin: 20px 0;">
        <div class="con1-l">
          <div class="con1-l-t">新闻中心</div>
            <ul class="iauth">
              <% $newses[0,5].each do |service| %>
                  <li>
                      <%=link_to truncate(service.name,length: 14), "/index/news/#{service.id}", title: service.name %>
                  </li>
              <% end %>
            </ul>
          </div>
          <div class="clear"></div>
      </div>


  </div>

app/views/index/about.html.erb
<%= render "left" %>
<div style="float: left; height: auto; width: 70%; padding-left: 100px; word-wrap:break-word">
  <!--面包屑-->
  <div class="crumb">
    <span style="font-size: 300%; padding-left: 20px;">联系我们</span>
    <div style="float: right; padding-top: 30px; padding-right: 20px;">
      <span>联系我们</span> > <span><%= $intro.name %></span>
    </div>
  </div>

  <!--正文-->
  <div class="context">

     <!--图片-->
    <div class="coim">
      
      <br/>
      <p>
        <span class="trn">公司法人:</span><span class="trv"> <%= $intro.user %></span>
      </p>
      <p>
        <span class="trn">公司地址:</span><span class="trv"> <%= $intro.addr %></span>
      </p>
      <p>
        <span class="trn">联系电话:</span><span class="trv"> 0510-81151545</span>
      </p>
            <p>
        <span class="trn">手机:</span><span class="trv"> <%= $intro.tel %></span>
      </p>
      <p>
        <span class="trn">email:</span><span class="trv"> <%= $intro.email %></span>
      </p>
    </div>



  </div>


  <div class="demo_line_01"><%= $intro.name %></div>
</div>

app/views/index/case.html.erb
<%= render "left" %>
<style type="text/css">

</style>

<div style="float: left; height: auto; width: 70%; padding-left: 100px; word-wrap:break-word">
  <!--面包屑-->
  <div class="crumb">
    <span style="font-size: 300%; padding-left: 20px;"><%= @case.name %></span>
    <div style="float: right; padding-top: 30px; padding-right: 20px;">
      <span>工程案例</span> > <span></span>
    </div>
  </div>

  <!--正文-->
  <div class="context">
    <h1 style="  ">
      <%= @case.name %>
    </h1>
    <!--图片-->
    <div class="coim">
      <%= image_tag @case.image_url %>
    </div>
    <div class="bbm ">
      <h3>
        详情介绍
      </h3>
    </div>
    <div style="min-height: 300px;">
      <%=sanitize @case.context %>
    </div>
  </div>

 <div class="demo_line_01"><%= $intro.name %></div>

<!--其他问题-->
<div class="bbm">
   <h3>
      其他案例：
   </h3>
 </div> 

  <ul class="oth">
     <% @cases[0,4].each do |ca| %>
        <li style="float: left; margin: 0 5px; text-align:center;">
          <a>
            <%= image_tag ca.image_url %>
            <br/>
            <span><%= ca.name %></span>
          </a>
        </li>
     <% end %>
   </ul>
</div>

app/views/index/cases.html.erb
cases.html.erb

app/views/index/index.html.erb
<% content_for :bannner do %>
    <div class="bannner"> 
        <div id="slider" class="nivoSlider">
            <% $advts.each do |advt|%> 
                
                    <a target="_blank"><img src="<%= advt.image_url %>" alt="#" title="" width="1920" height="520" /></a>
                
            <% end%>  
        </div>  
    </div>
<% end %>




  <div class="case">
      <div class="index-t"><p>推荐服务</p><a href="/index/product">+More</a><div class="clear"></div></div>
        <div class="con3-c iborder">
                <div id="demoo" style="overflow:hidden;height:auto;width:1160px; margin:0px auto;">
                  <table cellpadding="0" cellspace="0" border="0">
                    <tr>
                    <td id="demoo1">
                    <table border="0" cellspacing="0" cellpadding="0">
                    <tr>
                        <% $products.each do |product| %>
                            <td>
                                <%= link_to "/index/product/#{product.id}" do %>
                                    <%= image_tag product.image_url, width: "275", height: "215", alt:  product.service.try(:name).to_s %>
                                    <p><%= product.service.name%></p>
                                <% end %>
                            </td>
                        <% end %>
                    </tr>
                    </table>
                    </td>
                    <td id="demoo2"></td>
                    </tr>
                  </table>
                </div>
                
                <script>
                var speed=30
                var MyMar=setInterval(Marquee,speed)
                demoo2.innerHTML=demoo1.innerHTML
                demoo.onmouseover=function() {clearInterval(MyMar)}
                demoo.onmouseout=function() {MyMar=setInterval(Marquee,speed)}
                function Marquee(){
                if(demoo2.offsetWidth-demoo.scrollLeft<=0)
                demoo.scrollLeft-=demoo1.offsetWidth
                else{
                demoo.scrollLeft++
                }
                }
                </script>
            </div>
    </div>
    
    <!----about---->
  <div class="con2">
      <div class="con2-l">
          <div class="index-t"><p>公司介绍</p><a href="/index/intro">+More</a><div class="clear"></div></div>
            <div class="con2-l-c">
                    <!-- <img src="Public/images/about.png" /> -->
                    <%#= image_tag $intro.image_url%>
                    <div class="about-r">
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <%= $intro.name %>坐落于美丽的太湖之滨—无锡。是经江苏省无锡市工商局、环保局批准的专业从事环保工程；市政管道清洗疏通工程；工业废水、污水化粪池处理工程为一体的大型综合性工程服务公司。<br />
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;欢迎新老客户随时来电咨询洽谈，希望我们的事业发展能得到您们大力支持，预祝我们合作愉快 ！<br />
                    </div>
            </div>
        </div>
        <div class="con2-ce">
          <div class="index-t"><p>新闻中心</p><a href="/index/news">+More</a><div class="clear"></div></div>
            <div class="newstop1">
                   
                    <div class="newstop1-r" style="width: 410px;">
                        <p>
                            <%= link_to truncate($newses.first.try(:name)||"", length: 25), "/index/news/#{$newses.first.try(:id)}" %>
                        </p>
                        <span>
                            <%= truncate($newses.first.try(:desc), length: 40) %>
                        </span>
                    </div>
                    <div class="clear"></div>
                </div>            
                <ul class="indexnewslist">
                    <% $newses[1,5].to_a.each do |news|%>
                        <li>
                            <%= link_to truncate( news.name, length: 20), "/index/news/#{news.id}" %>
                            <span><%= news.created_at.strftime("%Y-%m-%d") %></span>
                        </li>
                    <% end %>
                </ul>
        </div>
        <div class="con2-r">
          <div class="index-t1"><p>联系我们</p></div>
            <div class="con2-c-c">
               <p><%= $intro.name %></p>
                地址：<%= $intro.addr %><br />
                电话：0510-81151545<br />
                手机：<%= $intro.tel %><br />
                联系人：<%= $intro.user %><br />
                网址：www.wxhjj.com<br/>
            </div>
        </div>
        <div class="clear"></div>
    </div>
    <!----about---->
    
  <div class="con1">
      <div class="con1-l">
        <div class="con1-l-t">服务项目 Service Items</div>
          <ul class="iauth">
            <% $services.each do |service| %>
                <li>
                    <%=link_to service.name, "", title: service.name %>
                </li>
            <% end %>
          </ul>
        </div>
        <div class="con1-r">
          <div class="index-t"><p>服务项目</p><a href="/index/product">+More</a><div class="clear"></div></div>
          <ul class="cp_list">
                <% $products[0,6].to_a.each do |product| %>
                    <li>
                        <%= link_to "/index/product/#{product.id}", title: product.name do%>
                            <%= image_tag product.image_url, alt: product.name%>
                            <p> <%= product.name  %> </p>
                        <% end %>
                    </li>
                <% end %>
                <div class="clear"></div>
            </ul>
        </div>
        <div class="clear"></div>
    </div>
  
    <!----case---->
    <div class="case">
      <div class="index-t"><p>工程案例</p><a href="/index/case">+More</a></div>
        <div class="con3-c iborder">
                <div id="caseo" style="overflow:hidden; height:auto;width:1160px;margin:0 auto; margin:0px auto; ">
                  <table cellpadding="0" cellspace="0" border="0">
                    <tr>
                        <td id="case1">
                            <table border="0" cellspacing="0" cellpadding="0">
                                <tr>
                                <% $cases.each do |ca| %>
                                    <td>
                                        <%=link_to  "/index/case/#{ca.id}", title: ca.name  do %>
                                            <%= image_tag ca.image_url, width: "275", height: "215" %>
                                            <p><%= ca.name %></p>
                                        <% end  %>
                                    </td>
                                <% end %>
                                                  
                                </tr>
                            </table>
                        </td>
                    <td id="case2"></td>
                    </tr>
                  </table>
                </div>
                
                <script>
                var speed=30
                var MyMar=setInterval(Marquee,speed)
                case2.innerHTML=case1.innerHTML
                caseo.onmouseover=function() {clearInterval(MyMar)}
                caseo.onmouseout=function() {MyMar=setInterval(Marquee,speed)}
                function Marquee(){
                if(case2.offsetWidth-caseo.scrollLeft<=0)
                caseo.scrollLeft-=case1.offsetWidth
                else{
                caseo.scrollLeft++
                }
                }
                </script>
            </div>
    </div>
    <!----case---->
<div class="clear"></div>
    <!----news---->
    <div class="news">
            <div class="news-l">
            <div class="inews-t">
            <div class="new-t">
                <%= link_to "新闻中心" , "/index/news", class: "hyxw" %>
            </div>
            <a href="/index/news" class="newsmore">+More</a>
            </div>
            <div class="news-c">
                <div class="gsxwc">
                    <div class="newstop">
                        <% if @news.present? %>
                        
                        <div class="newstop-r" style="width: 600px;">
                            <p>
                                <%= link_to @news.try(:name)||"", "/index/news/#{@news.try(:id)}" %>
                            </p>
                            <span>
                                <%= truncate @news.try(:desc), length: 90%>
                            </span>
                                <%= link_to "查看更多", "/index/news/#{@news.try(:id)}", class: "more" %>
                        </div>
                        <div class="clear"></div>
                        <% end %>
                    </div>                    
                        <ul class="newslist">
                            <% $newses[1,10].to_a.each do |news|%>
                                <li>
                                    <%= link_to news.name, "/index/news/#{news.id}"    %>
                                    <span>[<%= news.created_at.strftime("%Y-%m-%d")%>]</span>
                                </li>
                            <% end %>
                        </ul>
                </div>

               
            </div>
        </div>
        </div>
        <div class="news-r">
            <div class="cjwt-t"><p>常见问题</p></div>
            <div class="news-c-r">
                <div id="udemo" style="OVERFLOW: hidden; WIDTH: 440px; margin:0 auto; HEIGHT: 381px; ">
                    <table border="0" cellpadding="0" cellspacing="0">
                    <tr>
                       <td id="udemo1">
                            <table width="100%" height="99" border="0" cellpadding="0" cellspacing="0">
                                    <tr>
                                        <td>
                                         <ul class="i-question">
                                            <% $questions.each do |question| %>
                                                <li>
                                                    <p class="que1">
                                                        <%= link_to question.name, "/index/question/#{question.id}" %>
                                                    </p>
                                                    <p class="que2">
                                                        <%= truncate(question.desc, length: 25,truncate_string: "...")%>
                                                        <%= link_to "[详情]", "/index/question/#{question.id}" %>
                                                    </p>
                                                </li>
                                            <% end %>
                                         </ul>
                                        </td>
                                  </tr>
                            </table>
                        </td>
                    </tr>
                    <tr>
                       <td id="udemo2"></td>
                    </tr>
                    </table>
                </div>
                <SCRIPT>
                var speed=30
                var MyMarh=setInterval(Marqueeh,speed)
                udemo2.innerHTML=udemo1.innerHTML
                //原理是不断的向demoh2中填入demoh1中的内容，然后将已经看不见的清除
                //用一个两行一列的表格，上一列再放一个装填有内容的表格，定义为demoh1，下一列是空的TD，定义为demoh2
                //SPEED是用来控制速度的。
                udemo.onmouseover=function(){ clearInterval(MyMarh) }
                udemo.onmouseout=function(){ MyMarh=setInterval(Marqueeh,speed) }
                function Marqueeh(){
                if(udemo2.offsetHeight-udemo.scrollTop<=0)
                   udemo.scrollTop-=udemo1.offsetHeight
                else{
                   udemo.scrollTop++
                }
                }
                </SCRIPT>
            </div>
        </div>
        <div class="clear"></div>

    <div class="links">
      <div class="links-titl"><a href="#" class="yq">友情链接</a></div>
        <div class="links-c">
          <ul class="fenz">
            <div class="clear"></div>
            </ul>
            <ul class="ilink" style="display:none;">  
              <div class="clear"></div>
            </ul>
        </div>
    </div>

app/views/index/intro.html.erb
<%= render "left" %>
<div style="float: left; height: auto; width: 70%; padding-left: 100px; word-wrap:break-word">
  <!--面包屑-->
  <div class="crumb">
    <span style="font-size: 300%; padding-left: 20px;">公司简介</span>
    <div style="float: right; padding-top: 30px; padding-right: 20px;">
      <span>公司简介</span> > <span><%= $intro.name %></span>
    </div>
  </div>

  <!--正文-->
  <div class="context">
    <h1 >
      <%= $intro.name %>
    </h1>
     <!--图片-->
    <div class="coim">
      <%= image_tag $intro.image_url %>
      <br/>
      <p>
        <span class="trn">公司法人:</span><span class="trv"> <%= $intro.user %></span>
      </p>
      <p>
        <span class="trn">公司地址:</span><span class="trv"> <%= $intro.addr %></span>
      </p>
    
      <p>
        <span class="trn">联系电话:</span><span class="trv">   0510-81151545 </span>
      </p>
      <p>
        <span class="trn">手机号码:</span><span class="trv"> <%= $intro.tel %></span>
      </p>
      <p>
        <span class="trn">email:</span><span class="trv"> <%= $intro.email %></span>
      </p>
    </div>
    <div class="bbm ">
      <h3>
        详情介绍
      </h3>
    </div>
    <div style="min-height: 300px;">
      <%=sanitize $intro.context %>
    </div>


  </div>

  <!--分隔符-->
  <div class="demo_line_01"><%= $intro.name %></div>

  <!--其他问题-->
  <div class="bbm">
     <h3>
        服务项目：
     </h3>
   </div> 

    <ul class="oth">
       <% @service_items[0,4].each do |service_item| %>
          <li style="float: left; margin: 0 5px; text-align:center;">
            <%= link_to "/index/product/#{service_item.id}" do  %>
              <%= image_tag service_item.image_url %>
              <br/>
              <span><%= service_item.name %></span>
            <% end %>
          </li>
       <% end %>
    </ul>
  </div>
</div>

app/views/index/news.html.erb
<%= render "left" %>
<div style="float: left; height: auto; width: 70%; padding-left: 100px; word-wrap:break-word">
  <!--面包屑-->
  <div class="crumb">
    <span style="font-size: 30px; padding-left: 20px;"><%= @news.name %></span>
    <div style="float: right; padding-top: 30px; padding-right: 20px;">
      <span>新闻中心</span> > <span><%=truncate( @news.name, length: 15) %> </span>
    </div>
  </div>

  <!--正文-->
  <div class="context">
    <h1  style="border-bottom-style: none;margin-bottom: 20px;">
      <%= @news.name %>
    </h1>
    <span style="padding-left: 150px; "> 发布时间: <%= @news.created_at.strftime("%Y-%m-%m %H:%M") %></span>
    <span style="padding-left: 10px; "> 发布者: <%= $intro.name %></span>
    <div style="min-height: 300px; margin: 20px 0; font-size: 16px;">
      <%=sanitize @news.context %>
    </div>
  </div>

    <!--分隔符-->
  <div class="demo_line_01"><%= $intro.name %></div>

<div class="bbm">
   <h3>
      最新新闻：
   </h3>
 </div> 
<!--其他新闻-->
  <ul class="indexnewslist">
      <% @newses[0,6].each do |news|%>
          <li style="border-bottom: 1px dashed; margin-bottom: 4px; ">
              <%= link_to  news.name, "/index/news/#{news.id}" %>
              <span><%= news.created_at.strftime("%Y-%m-%d") %></span>
          </li>
      <% end %>
  </ul>
</div>

app/views/index/newses.html.erb
newses.html.erb

app/views/index/product.html.erb
<%= render "left" %>
<div style="float: left; height: auto; width: 70%; padding-left: 100px; word-wrap:break-word">
  <!--面包屑-->
  <div class="crumb">
    <span style="font-size: 300%; padding-left: 20px;"><%= @service_item.name %></span>
    <div style="float: right; padding-top: 30px; padding-right: 20px;">
      <span>服务项目</span> > <span><%= @service_item.service.try(:name) %></span>
    </div>
  </div>

  <!--正文-->
  <div class="context">
    <h1 >
      <%= @service_item.service.try(:name) %>
    </h1>
    <!--图片-->
    <div class="coim">
      <%= image_tag @service_item.image_url %>
    </div>
    <div class="bbm ">
      <h3>
        详情介绍
      </h3>
    </div>
    <div style="min-height: 300px;">
      <%= raw  @service_item.content %>
    </div>
  </div>

  <!--分隔符-->
  <div class="demo_line_01"><%= $intro.name %></div>

<!--其他问题-->
<div class="bbm">
   <h3>
      其他项目：
   </h3>
 </div> 

  <ul class="oth">
     <% @service_items[0,4].each do |service_item| %>
        <li style="float: left; margin: 0 5px; text-align:center;">
          <%= link_to "/index/product/#{service_item.id}" do  %>
            <%= image_tag service_item.image_url %>
            <br/>
            <span><%= service_item.name %></span>
          <% end %>
        </li>
     <% end %>
   </ul>
</div>

app/views/index/products.html.erb
products.html.erb

app/views/index/question.html.erb
<%= render "left" %>
<div style="float: left; height: auto; width: 70%; padding-left: 100px; word-wrap:break-word">
  <!--面包屑-->
  <div class="crumb">
    <span style="font-size: 300%; padding-left: 20px;"><%= @question.name %></span>
    <div style="float: right; padding-top: 30px; padding-right: 20px;">
      <span>常见问题</span> > <span><%= @question.name %> </span>
    </div>
  </div>


  <!--正文-->
  <div class="context">
    <h1  style="border-bottom-style: none ">
      <%= @question.name %>
    </h1>
    <div class="bbm ">
      <h3>
        详情介绍
      </h3>
    </div>
    <div style="min-height: 300px;">
      <%=sanitize @question.context %>
    </div>
  </div>

  <!--分隔符-->
  <div class="demo_line_01"><%= $intro.name %></div>

<!--其他问题-->
<div class="bbm">
   <h3>
      常见问题：
   </h3>
 </div> 

  <!--其他问题-->
  <ul class="i-question">
      <% @questions.each do |question| %>
          <li>
              <p class="que1">
                  <%= link_to question.name, "/index/question/#{question.id}" %>
              </p>
              <p class="que2">
                  <%= truncate(question.desc, length: 25,truncate_string: "...")%>
                  <%= link_to "[详情]", "/index/question/#{question.id}" %>
              </p>
          </li>
      <% end %>
   </ul>
</div>

app/views/index/questions.html.erb
questions.html.erb

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>后台管理</title>
  <%= stylesheet_link_tag 'admin', media: 'all'%>
  <%= javascript_include_tag 'admin'%>
  <%= csrf_meta_tags %>
</head>
<body>
<main>
  <header>
    <a class="logo"><i class=" pr10 f18"></i>后台管理</a>
    <a href="/admin/sign_out" class="close"><i class=" pr10"></i>退出</a>
  </header>
  <nav class="sidebar">
    <ul>
        <li class="<%= 'active' if controller_name == 'intros' %>">
          <%= link_to "公司介绍", admin_intros_path %><i class=" arrow"></i>
        </li>
         <li class="<%= 'active' if controller_name == 'services' %>">
          <%= link_to "服务项目", admin_services_path %><i class=" arrow"></i>
        </li>
        <li class="<%= 'active' if controller_name == 'service_items' %>">
          <%= link_to "服务项目内容", admin_service_items_path %><i class=" arrow"></i>
        </li>
        <li class="<%= 'active' if controller_name == 'advts' %>">
          <%= link_to "广告图", admin_advts_path %><i class=" arrow"></i>
        </li>
        <li class="<%= 'active' if controller_name == 'newes' %>">
          <%= link_to "新闻中心", admin_newses_path %><i class=" arrow"></i>
        </li>
         <li class="<%= 'active' if controller_name == 'questions' %>">
          <%= link_to "常见问题", admin_questions_path %><i class="fa  arrow"></i>
        </li>
        <li class="<%= 'active' if controller_name == 'cases' %>">
          <%= link_to "工程案例", admin_cases_path %><i class="fa arrow"></i>
        </li>
       
    </ul>
  </nav>
  <div class="con">
    <%= yield %>
  </div>
  <footer>
    
  </footer>
</main>
<script type="text/javascript">
    function WindowResize(){
     setTimeout(function(){
      if($(document).height()>$(window).height()){
        $("html").css("height","auto");
       }else{
        $("html").css("height","100%");
       }
     },100);
    }
    $(window).resize(function(){
      WindowResize();
    });
    $(window).load(function(){
      WindowResize();
    });
  </script>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Xia</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>